# permissions for end users to view games.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: game-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder
    app.kubernetes.io/part-of: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: game-viewer-role
rules:
- apiGroups:
  - myapp.qingwave.github.io
  resources:
  - games
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - myapp.qingwave.github.io
  resources:
  - games/status
  verbs:
  - get
